package org.openCage.artigen;

import org.apache.commons.io.IOUtils;
import org.jetbrains.annotations.NotNull;
import org.openCage.fspath.protocol.FSPath;
import org.openCage.io.clazz.FileExistence;
import org.openCage.lang.artifact.Artifact;
import org.openCage.lang.artifact.Project;
import org.openCage.lang.errors.Unchecked;

import java.io.FileWriter;
import java.io.IOException;

/**
 * Created by IntelliJ IDEA.
 * User: stephan
 * Date: Apr 16, 2010
 * Time: 10:59:26 AM
 * To change this template use File | Settings | File Templates.
 */
public class PElephGen {

    private final Project project;

    public PElephGen( @NotNull Project project ) { //}, FSPath baseDir  ) {
        this.project = project;
    }

    public void generate( FSPath projectRoot ) {

        FSPath rootPom = projectRoot.add( "dependencies.xml" );
        FileExistence.ensurePath( rootPom );

        FileWriter writer = null;
        try {
            writer = new FileWriter( rootPom.toFile() );

            writer.write( deps());

        } catch (IOException e) {
            throw Unchecked.wrap( e );
        } finally {
            IOUtils.closeQuietly( writer );
        }

        for ( Artifact mod : project.getModules() ) {
            FSPath modPom = projectRoot.add( "modules", mod.gettName(), "build.xml" );
            FileExistence.ensurePath( modPom );

            try {
                writer = new FileWriter( modPom.toFile() );

                writer.write( buildxml( mod ));

            } catch (IOException e) {
                throw Unchecked.wrap( e );
            } finally {
                IOUtils.closeQuietly( writer );
            }

        }
    }



    public String buildxml( Artifact arti ) {
        String ret = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +
                "<project name=\"" + arti.gettName() + "\" default=\"default\" basedir=\".\">\n\n" +
                "   <!-- generated by openCage-artifact -->\n\n";



        ret += antProperty( "el.version", arti.getVersion().getOriginal()) + "\n";
        ret += antProperty( "el.groupId", arti.getGroupId()) + "\n";
        ret += antProperty( "el.src", "src/main/java") + "\n";

        if ( arti.isApp() ) {
            ret += antProperty( "el.isApp", "true") + "\n";
            ret += antProperty( "el.main.class", arti.getMainClass() ) + "\n";            
        }

        ret += antProperty( "el.description.short", arti.getDescriptionShort()) + "\n";
        ret += antProperty( "el.licence", arti.getLicence().getName()) + "\n";

        ret += "\n   <import file=\"../../build-resources/build-common.xml\"/>\n" +
                "</project>";
        return ret;
    }

    private String antProperty( String key, String val ) {
        return "   <property name = \"" + key + "\"       value=\"" + val + "\" />";
    }

    public String deps() {
        String ret =
                "<?xml version=\"1.0\" encoding=\"ISO-8859-1\"?>\n" +
                "<project name=\"dependencies\">\n\n" +
                        "  <!-- ===== generated by openCage-artigen ======== -->\n\n" +
                "   <dirname property=\"dependencies.basedir\" file=\"${ant.file.dependencies}\"/>\n\n";


        for ( Artifact arti : project.getModules() ) {
            ret += writeModule(arti);
        }

        ret += "\n" +
                "   <!-- ================================================================== -->\n" +
                "   <!--     external library dependencies                                  --> \n" +
                "   <!-- ================================================================== -->    \n" +
                "\n";

        for ( Artifact arti : project.getExternals()) {
            ret += writeExternal(arti);
        }

        ret += "\n\n</project>\n";


        
        return ret;
    }

    //    <!-- ================================================================== -->
    //    <target name= "launch4j"
    //            depends="xstream">
    //        <copy todir="${dependencies.basedir}/build/libs" file="${dependencies.basedir}/external/production/launch4j.jar"/>
    //    </target>
    private String writeExternal(Artifact arti) {
        String ret = "   <!-- ================================================================== -->\n";
        ret += "   <target name=\""+ arti.gettName() +"\"";

        if ( arti.getCompileDependencies().size() > 0 ) {
            ret += "\n           depends=\"";

            for ( org.openCage.lang.count.Count<Artifact> dep : org.openCage.lang.count.Count.count(arti.getCompileDependencies()) ) {
                ret += dep.obj().gettName();
                if ( !dep.isLast()) {
                    ret += ", ";
                }
            }
            ret += "\"";
        }

        ret += ">\n";

        ret += "      <copy todir=\"${dependencies.basedir}/build/libs\" file=\"${dependencies.basedir}/repo/"+ getLibraryLocation( arti )+"\" />\n";

        ret += "   </target>\n\n";
        return ret;
    }

    private String getLibraryLocation(Artifact arti) {
        return arti.getGroupId().replace('.', '/')  + "/" + arti.gettName() + "/" + arti.getVersion().getOriginal() + "/" + arti.gettName() + "-" + arti.getVersion().getOriginal() + ".jar" ;
    }

    //    <!-- ================================================================== -->
    //    <target name= "depend.ui"
    //            depends="depend.localization, depend.application, depend.io, designgridlayout, depend.lang, guice, javagraphics-preferencepanel, RSyntaxTextArea, jgoodies-binding">
    //        <ant dir="${dependencies.basedir}/modules/ui" target="local.goal" inheritAll="false"/>
    //    </target>
    private String writeModule(Artifact arti) {
        String ret = "   <!-- ================================================================== -->\n";
        ret += "   <target name=\""+ getModuleName(arti ) +"\"";

        if ( arti.getCompileDependencies().size() > 0 ) {
            ret += "\n           depends=\"";

            for ( org.openCage.lang.count.Count<Artifact> dep : org.openCage.lang.count.Count.count(arti.getCompileDependencies()) ) {
                ret += getModuleName( dep.obj() );
                if ( !dep.isLast()) {
                    ret += ", ";
                }
            }
            ret += "\"";
        }
        ret += ">\n";
        ret += "      <ant dir=\"${dependencies.basedir}/modules/" + arti.gettName() + "\""
            +      " target=\"local.goal\" inheritAll=\"false\"/>\n";

        ret += "   </target>\n\n";
        return ret;
    }

    private String getModuleName( Artifact arti ) {

        if ( project.isModule( arti )) {
            return "depend." + arti.gettName();
        }

        return arti.gettName();
    }
}
