/*
 * ComicEditor2.java
 *
 * Created on November 20, 2004, 11:53 AM
 */

import java.util.*;

/**
 *
 * @author  oc
 */
public class ComicEditor extends javax.swing.JDialog {
    
    /** Creates new form ComicEditor2 */
    public ComicEditor(java.awt.Frame parent, boolean modal, Comic comic ) {
        super(parent, modal);
        this.comic = comic;
        initComponents();
        
        jTextFieldName.setText( comic.getName() );
        jLabelArtists.setText( comic.getArtistsText() );
        jList1.setListData( comic.getUrls() );
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jLabelArtists = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButtonArtists = new javax.swing.JButton();
        jButtonUrls = new javax.swing.JButton();
        jLabelBuffer1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxRating = new javax.swing.JComboBox( comic.getRatingTexts() );
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButtonGo = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabelLanguages = new javax.swing.JLabel();
        jButtonLanguages = new javax.swing.JButton();

        getContentPane().setLayout(new java.awt.GridBagLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jLabel1.setText("Artists");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        getContentPane().add(jLabel1, gridBagConstraints);

        jLabelArtists.setText("a,b");
        jLabelArtists.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelArtistsMouseClicked(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(jLabelArtists, gridBagConstraints);

        jLabel3.setText("Name");
        getContentPane().add(jLabel3, new java.awt.GridBagConstraints());

        jTextFieldName.setText("foo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(jTextFieldName, gridBagConstraints);

        jLabel2.setText("Urls");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        getContentPane().add(jLabel2, gridBagConstraints);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(259, 50));
        jScrollPane1.setViewportView(jList1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jScrollPane1, gridBagConstraints);

        jButtonArtists.setText("...");
        jButtonArtists.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonArtistsActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        getContentPane().add(jButtonArtists, gridBagConstraints);

        jButtonUrls.setText("...");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        getContentPane().add(jButtonUrls, gridBagConstraints);

        jLabelBuffer1.setText("  ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        getContentPane().add(jLabelBuffer1, gridBagConstraints);

        jLabel4.setText("Rating");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        getContentPane().add(jLabel4, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(jComboBoxRating, gridBagConstraints);

        jLabel5.setText("    ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        getContentPane().add(jLabel5, gridBagConstraints);

        jLabel6.setText("  ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        getContentPane().add(jLabel6, gridBagConstraints);

        jButtonGo.setText("Go");
        jButtonGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGoActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        getContentPane().add(jButtonGo, gridBagConstraints);

        jLabel7.setText("Languages");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        getContentPane().add(jLabel7, gridBagConstraints);

        jLabelLanguages.setText("jLabel8");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 1;
        getContentPane().add(jLabelLanguages, gridBagConstraints);

        jButtonLanguages.setText("...");
        jButtonLanguages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLanguagesActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 1;
        getContentPane().add(jButtonLanguages, gridBagConstraints);

        pack();
    }//GEN-END:initComponents

    private void jButtonLanguagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLanguagesActionPerformed
        new MultiPropCombo( new javax.swing.JFrame(), true, "Languages", comic.getLanguageTexts(), comic.getLanguages()).show();
    }//GEN-LAST:event_jButtonLanguagesActionPerformed

    private void jButtonGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGoActionPerformed
        if ( jList1.getSelectedIndices() != null ) {
            BrowseToUrl.displayURL( (String)jList1.getSelectedValue() );
        }
    }//GEN-LAST:event_jButtonGoActionPerformed

    private void jButtonArtistsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonArtistsActionPerformed
        MultiPropString prop = new MultiPropString(new javax.swing.JFrame(), true, "Artists", comic.getArtists() );
        prop.show();
    }//GEN-LAST:event_jButtonArtistsActionPerformed

    private void jLabelArtistsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelArtistsMouseClicked

        Vector artists = new Vector();
        artists.add("a");
        artists.add("b");
        MultiPropString prop = new MultiPropString(new javax.swing.JFrame(), true, "daaa", artists );
        
        prop.show();
    }//GEN-LAST:event_jLabelArtistsMouseClicked
    
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        new ComicEditor2(new javax.swing.JFrame(), true).show();
//    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonArtists;
    private javax.swing.JButton jButtonGo;
    private javax.swing.JButton jButtonLanguages;
    private javax.swing.JButton jButtonUrls;
    private javax.swing.JComboBox jComboBoxRating;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelArtists;
    private javax.swing.JLabel jLabelBuffer1;
    private javax.swing.JLabel jLabelLanguages;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldName;
    // End of variables declaration//GEN-END:variables

    private Comic comic;
}
