/*
 * Languages.java
 *
 * Created on 19. September 2004, 16:03
 */

import java.util.*;
import javax.swing.*;
import java.awt.*;

/**
 *
 * @author  Stephan
 */
public class Languages extends javax.swing.JPanel {
    
    /** Creates new form Languages */
    public Languages() {
        initComponents();
        
        boxes = new Vector();
        
        for ( int i = 0; i < 10; i++ ) {
            boxes.add( new JComboBox( Comic.getLanguageTexts()) );
        }
        
        showing = 0;
        showMore();
        
    }
    
    
    public void setTopFrame( JFrame frame ) {
        topFrame = frame;
    }
    
    private void repaintTop() {
        if ( topFrame != null ) {
            topFrame.repaint();
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        setBorder(new javax.swing.border.EtchedBorder());
        setFont(new java.awt.Font("Verdana", 0, 10));
        setMinimumSize(new java.awt.Dimension(250, 100));
        setPreferredSize(new java.awt.Dimension(0, 0));
        jLabel1.setFont(new java.awt.Font("Verdana", 0, 10));
        jLabel1.setText("Languages");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(jLabel1, gridBagConstraints);

        jButton1.setFont(new java.awt.Font("Verdana", 0, 10));
        jButton1.setText("+");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        add(jButton1, gridBagConstraints);

        jButton2.setText("-");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        add(jButton2, gridBagConstraints);

    }//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        showMore();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void showMore() {
        GridBagConstraints gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = showing;
        gridBagConstraints.gridwidth = 2;
        
        add( (JComboBox)boxes.get(showing), gridBagConstraints );
        
        ((JComboBox)boxes.get(showing)).setVisible(true);
        
        showing++;                                
        repaintTop();

    }
    
//    public int getHeight() {
//        return (showing + 2) * 22 + 22;
//    }
    
//    public Dimension getSize() {
//        return new Dimension( 1000, 300 );
//    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    private Vector boxes;
    private int    showing;
    private JFrame topFrame;
}
