/*
 * Urls.java
 *
 * Created on September 20, 2004, 4:26 PM
 */

import java.util.*;
import javax.swing.*;

/**
 *
 * @author  SPfab
 */
public class Urls extends javax.swing.JPanel {
    
    /** Creates new form Urls */
    public Urls() {
        initComponents();
        showing = 0;
        urls = new Vector();
        showMore();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        jButton1.setText("+");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        add(jButton1, gridBagConstraints);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.weighty = 2.0;
        add(jPanel1, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 10));
        jLabel1.setText("Urls");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        add(jLabel1, gridBagConstraints);

        jButton2.setFont(new java.awt.Font("Verdana", 0, 10));
        jButton2.setText("-");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        add(jButton2, gridBagConstraints);

    }//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        showMore();
    }//GEN-LAST:event_jButton1ActionPerformed
    
//    public int getHeight() {
//        return (showing + 2)* 22;
//    }
    
    public void setTopFrame( JFrame frame ) {
        topFrame = frame;
    }
    
    public void showMore() {
        
        SingleUrl surl = new SingleUrl();
        jPanel1.add( surl );
        urls.add( surl );
        surl.setVisible( true );
        
        showing++;
        repaintTop();

    }

    private void repaintTop() {
        if ( topFrame != null ) {
            topFrame.repaint();
            repaint();
        }
    }
    
    private int    showing;
    private Vector urls;
    private JFrame topFrame;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    
}
